### ISSUE TITLE
Error on multipalyer

### ISSUE THREAD

**Issue by xlly-s2** [Papela/Nitrox-Cracked-Mod#10]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

![Screenshot 2024-04-30 174038](https://github.com/Papela/Nitrox-Cracked-Mod/assets/156248534/0361e212-3b95-4fc8-bd7f-59884e6272a9)

**Comment by Papela** [comment]
**Fixed in a discord conversation**
