### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kiosic** [Papela/Nitrox-Cracked-Mod#11]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

![Screenshot 2024-05-25 122125](https://github.com/Papela/Nitrox-Cracked-Mod/assets/170784899/8f10a980-7d86-4002-8f0c-4d81a21c2111)

### Describe the steps you took to encounter the bug.

when i press multiplayer it po up an error i already try running on adminstrator but it still doesnt work same as my brother too

### Relevant log output

[21:21:31.194] [ERR] Could not locate Subnautica installation directory: 
Configured game path was found empty. Please enter the path to the Subnautica installation.
It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
Could not find Subnautica installation directory from Epic Games installation records. Verify that Subnautica has been installed with Epic Games Store.
Configured game path with environment variable SUBNAUTICA_INSTALLATION_PATH was found empty.
[21:21:31.252] [ERR] Could not locate Subnautica installation directory: 
Configured game path was found empty. Please enter the path to the Subnautica installation.
It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
Could not find Subnautica installation directory from Epic Games installation records. Verify that Subnautica has been installed with Epic Games Store.
Configured game path with environment variable SUBNAUTICA_INSTALLATION_PATH was found empty.
[21:21:31.258] [ERR] Could not locate Subnautica installation directory: 
Configured game path was found empty. Please enter the path to the Subnautica installation.
It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
Could not find Subnautica installation directory from Epic Games installation records. Verify that Subnautica has been installed with Epic Games Store.
Configured game path with environment variable SUBNAUTICA_INSTALLATION_PATH was found empty.
[21:21:31.260] [ERR] Could not locate Subnautica installation directory: 
Configured game path was found empty. Please enter the path to the Subnautica installation.
It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
Could not find Subnautica installation directory from Epic Games installation records. Verify that Subnautica has been installed with Epic Games Store.
Configured game path with environment variable SUBNAUTICA_INSTALLATION_PATH was found empty.
[21:21:31.357] [INF] Trying to request data from https://raw.githubusercontent.com/Papela/Online-Repos/main/Nitrox/latest.json
[21:21:31.439] [ERR] Could not locate Subnautica installation directory: 
Configured game path was found empty. Please enter the path to the Subnautica installation.
It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
Could not find Subnautica installation directory from Epic Games installation records. Verify that Subnautica has been installed with Epic Games Store.
Configured game path with environment variable SUBNAUTICA_INSTALLATION_PATH was found empty.
[21:21:31.440] [WRN] Tried to add firewall rule for program that does not exist: Subnautica.exe
[21:21:31.545] [INF] Trying to request data from https://raw.githubusercontent.com/Papela/Online-Repos/main/Nitrox/blog.json
[21:21:31.555] [INF] Trying to request data from https://raw.githubusercontent.com/Papela/Online-Repos/main/Nitrox/changelog.json
[21:21:32.714] [ERR] Could not locate Subnautica installation directory: 
Configured game path was found empty. Please enter the path to the Subnautica installation.
It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
Could not find Subnautica installation directory from Epic Games installation records. Verify that Subnautica has been installed with Epic Games Store.
Configured game path with environment variable SUBNAUTICA_INSTALLATION_PATH was found empty.

**Comment by kiosic** [comment]
btw i request a add friend on you in discord

**Comment by Papela** [comment]
What version of subnautica are you using?

**Comment by kiosic** [comment]
v72485

**Comment by kiosic** [comment]
do i have to change it?

**Comment by Papela** [comment]
Possibly, I don't remember the date of that version. But I recommend Dec-2023

**Comment by kiosic** [comment]
sorry but i dont really know how to donload a old version cause i use a website that cant download a old version would you mind sharing a file for that?

**Comment by Papela** [comment]
Try using [this](https://www.mediafire.com/file/56c8h575xlvk6vr/Subnautica+NitroxV1.8.1.zip/file).

**Comment by kiosic** [comment]
tysmmm

**Comment by kiosic** [comment]
i gonna try it out if it didnt work ill notifed you in discord ty

**Comment by kiosic** [comment]
!
