### ISSUE TITLE
Stuck in loading screen

### ISSUE THREAD

**Issue by thelsn** [Papela/Nitrox-Cracked-Mod#13]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Both me and my friend are unable to get into the game and it wasn't throwing any error and we just end up stuck in this screen

![image-min](https://github.com/user-attachments/assets/e660c23a-1f20-4a21-ba1b-f3d716246966)

### Describe the steps you took to encounter the bug.

We joined and played for a while then left and attempted to join and it wouldn't let us

### Relevant log output

[game-20240813.log](https://github.com/user-attachments/files/16605420/game-20240813.log)
[server-20240813.log](https://github.com/user-attachments/files/16605423/server-20240813.log)

**Comment by Papela** [comment]
It is probably due to some incompatibility with the version of the game used. Try using the Mar.-2023 (71288) version with the new version of nitrox (V1.8.0.2)
