### ISSUE TITLE
Error trying to start multiplayer

### ISSUE THREAD

**Issue by fudsquad** [Papela/Nitrox-Cracked-Mod#14]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

lanucher will not load due to the error below
![image_2024-08-16_180350751](https://github.com/user-attachments/assets/bb07773e-9e47-4349-a3ae-5853d7aa9323)

### Describe the steps you took to encounter the bug.

Run the launcher as administrator 
Changed subnautica loctation
Tried to load multiplayer 
thats all

im on windows 10 as a note

### Relevant log output

System.InvalidOperationException: Sequence contains no matching element
at System.Linq.Enumerable. First[Source](IEnumerable`1 source, Func'2 predicate)
at
NitroxLauncher.Models.Patching.NitroxEntryPatch.Remove() in NitroxLauncher\Models\Patching\NitroxEntryPatch.cs:line
at
102
NitroxLauncher.LauncherLogic.<StartMultiplayerAsync>d__28. MoveNext() in NitroxLauncher\LauncherLogic.cs:line 228 --- End of stack trace from previous location where exception was thrown ---
at
System.Runtime.Exception Services. Exception Dispatchinfo.Thro
w0 at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSucc essAndDebuggerNotification(Task task)
at
NitroxLauncher.Pages.LaunchGamePage. <MultiplayerButton_C lick>d__8.MoveNext() in NitroxLauncher\Pages\LaunchGamePage.xaml.cs:line 49

**Comment by luckysaven** [comment]
subnautica updated their game so nitrox won't work with newest subnautica game.  find version 71288 subnautica crack version it work fine

**Comment by Papela** [comment]
Yes, also make sure the server has finished starting before running the game. In some cases it may hang and display a similar error.

**Comment by Vampirizm2021** [comment]
> subnautica updated their game so nitrox won't work with newest subnautica game. find version 71288 subnautica crack version it work fine
Where would I get that?

**Comment by Papela** [comment]
> > subnautica updated their game so nitrox won't work with newest subnautica game. find version 71288 subnautica crack version it work fine
> Where would I get that?
> 

Write me on Discord if you want: [@papela](https://discord.com/users/529736520048050189)
