### ISSUE TITLE
Bugs in building not saving and not seeing by other players

### ISSUE THREAD

**Issue by Kenwaynial** [Papela/Nitrox-Cracked-Mod#15]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

Hi good day sir ! , 

ask if u have solution of our problem in subnautica nitrox cracked which is when my friend build something his pov its done and my pov its just blueprint plus when we reconnect our build is being back to blueprints 

may i ask if theres something to fix it and the building resync what are the function of that if ever 

THANKYOU HOPING YOU TO REPLY !!!

![image](https://github.com/user-attachments/assets/43e4176d-96b4-4a3c-985e-457287f61dde)

**Comment by Papela** [comment]
I've released a new update, I haven't tested it yet to see if that bug has been fixed, but it would be nice to know. I recommend you play using version Mar-2023 (71288).
