### ISSUE TITLE
Port doesn't open

### ISSUE THREAD

**Issue by KATalyzt36** [Papela/Nitrox-Cracked-Mod#16]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### What version of Subnautica are you using?

La ultima de Epic Games al dia de la fecha,

### Describe the issue.

Ni el puerto 11000 ni el personalizado que puse funcionan, en LAN o Localhost si, pero abro los puertos manualmente en el router porque por UPnP no lo hace y al hacer ping a ese puerto con una herramienta online me dice que el puerto está cerrado. Abri un servidor de Minecraft con ese puerto en concreto y me dice que está abierto,

### Relevant log output

[00:02:53.700] Server started (275s)
[00:02:53.700] To get help for commands, run help in console or /help in chatbox
[00:02:53.964] Use IP to connect:
        127.0.0.1 - You (Local)
        Mi ip - Friends on another internet network (Port Forwarding)
 Y nada, puerto cerrado (36036 en este caso)

**Comment by Papela** [comment]
Este mod puede que no funcione correctamente en versiones muy nuevas de Subnautica. Te recomiendo usar la: mar.-2023 (71288)
He hecho pruebas y a mi me ha funcionado conectarme a mi servidor desde otro equipo en una red distinta. Te recomiendo que mires tu configuración del Firewall de Windows. Tal vez ese sea el culpable de que no puedan conectarte desde otras redes

**Comment by KATalyzt36** [comment]
@Papela Si, hay multiples problemas con todo eso... Uso la version de Epic Games, por lo que siempre será la ultima. Desactivé el firewall, abri los puertos en el router y nada, el UPnP como dije tampoco hizo nada. Incluso ejecutando como administrador no lo logra hacer :(
De que plataforma es tu version? La mia de Epic la empaquete en un .zip con un nombre random y con contraseña para pasarselo a algunos amigos, Pero claro, parece no estar funcionando. Estuve buscando la ultima previa a la 2.0 pero no sé que version de Build es, ni lo encontré en internet. Si tenes la de Epic, me lo podrias subir de la misma o una manera similar? Te lo re agradeceria jaja

**Comment by Papela** [comment]
Escríbeme al Discord: @Papela

**Comment by KATalyzt36** [comment]
@Papela Hum... Ya

**Comment by Papela** [comment]
Arreglado en discord
