### ISSUE TITLE
Error While starting in multiplayer mode

### ISSUE THREAD

**Issue by LusiveLoki** [Papela/Nitrox-Cracked-Mod#25]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### What version of Subnautica are you using?

71288

### Describe the issue.

![IMG_3372](https://github.com/user-attachments/assets/54314c5b-8dea-4cad-bb54-da29002ad8df)

### Describe the steps you took to encounter the bug.

Run nitrox in admin mode click on play multiplayer and it immediately shows up. It doesn’t let me run my server either

**Comment by Papela** [comment]
mmm, write me on discord: **papela**
