### ISSUE TITLE
Please write an informative title describing the bug in a few words

### ISSUE THREAD

**Issue by WhiteKapi** [Papela/Nitrox-Cracked-Mod#4]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

I tried with two different versions of Subnautica, when I click "play multiplayer" one of these pops up:
![er1](https://github.com/Papela/Nitrox-Cracked-Mod/assets/97306028/97a61e77-4a50-4b39-b92d-69b2f9f5927f)
![er2](https://github.com/Papela/Nitrox-Cracked-Mod/assets/97306028/2dfac69b-46fb-4cae-842c-3e507fe5004f)

**Comment by Papela** [comment]
What versions of Subnautica have you tried?

**Comment by DefaultUser9148** [comment]
@Papela 24.5.2023

**Comment by Papela** [comment]
try using this version: [Game+Nitrox](https://www.mediafire.com/file/56c8h575xlvk6vr/Subnautica+NitroxV1.8.1.zip/file)
