### ISSUE TITLE
hey! I have wasted like 2 hours for nothing because I've got a different type of error message, I don't understand whats the problem. Could anyone help me?

### ISSUE THREAD

**Issue by angrylettuce33** [Papela/Nitrox-Cracked-Mod#5]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Other

### Describe the issue.

![kép_2023-12-25_043642482](https://github.com/Papela/Nitrox-Cracked-Mod/assets/154773200/1595243e-039a-4306-9e66-98e6bd07dafe)

### Describe the steps you took to encounter the bug.

i re-downloaded the game twice because i tought it may help, but i think the problem is a really different thing. I use hamachi and the server is also runing because i see it on the console but if I open the game, it's just crashes and shows this error code or it is loads to singleplayer.

**Comment by angrylettuce33** [comment]
Btw sorry if you notice any mistake, my English is not good at all.

**Comment by Papela** [comment]
What version of the game are you using?
