### ISSUE TITLE
Multiplayer button not appearing

### ISSUE THREAD

**Issue by edy131109** [Papela/Nitrox-Cracked-Mod#6]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Other

### Describe the issue.

The multiplayer button isn't there.

### Describe the steps you took to encounter the bug.

Start the game from the launcher

**Comment by Papela** [comment]
My version of the mod is probably very outdated, I recommend that you try it with the Dec-2023 version. When I have time, I will try to re-release a new version.

**Comment by edy131109** [comment]
> My version of the mod is probably very outdated, I recommend that you try it with the Dec-2023 version. When I have time, I will try to re-release a new version.

Yeah I prob just don't have the right ver of subnautica
