### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by jovi-tsx** [Papela/Nitrox-Cracked-Mod#7]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Other

### Describe the issue.

![image](https://github.com/Papela/Nitrox-Cracked-Mod/assets/26393995/801a07cf-6fc4-4a60-b649-f7f25614e619)

Game folder is correct, i only press to play and receive this error

### Describe the steps you took to encounter the bug.

Downloaded version 19.01.2024, extracted this nitrox into game folder and opened it as admin, when you press to play either singleplayer or multiplayer, it gives you an error

**Comment by Papela** [comment]
My version of the mod is probably very outdated, I recommend that you try it with the Dec-2023 version. When I have time, I will try to re-release a new version.
