### ISSUE TITLE
Reword README and links

### ISSUE THREAD

**Issue by Jannify** [Papela/Nitrox-Cracked-Mod#8]
### Describe the issue

Hey,
while this repo is against our (the Nitrox-Team) values it's legal under the open-source ideals.

BUT we would like you to rewrite the README.md so it's not linking to our pages/services without a disclaimer that this repo is not from the Nitrox Team. Additionally, we would like you to remove the `.github/ISSUE_TEMPLATE/config.yml` with the link to our discord.

If you do not comply with this, we will unfortunately have to contact github and file a report for impersonation.

**Comment by Papela** [comment]
Understood and fixed 🫡
Thank you
