### ISSUE TITLE
Error while starting in multiplayer mode

### ISSUE THREAD

**Issue by iamdeepanshugarg** [Papela/Nitrox-Cracked-Mod#9]
### Are you on the latest version of Nitrox Cracked Mod?

Yes, I'm on the latest release of Nitrox Cracked Mod.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Error while starting in multiplayer mode
![image](https://github.com/Papela/Nitrox-Cracked-Mod/assets/144537531/67232906-dba0-49ee-8c7d-7314c3041f26)

**Comment by Papela** [comment]
**Fixed in a discord conversation**
